# Generated by Django 3.0.3 on 2020-02-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('degree', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
