# Generated by Django 3.0.3 on 2020-02-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
            ],
        ),
    ]
