# Generated by Django 3.0.3 on 2020-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='us2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
            ],
        ),
    ]
