# Generated by Django 3.0.3 on 2020-02-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0005_us2'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
            ],
        ),
    ]
